FROM alpine

COPY ./codes/memoriaOverhead.c /memoriaOverhead.c

RUN apk update &&\
    apk add build-base &&\
    apk add strace &&\
    gcc -o /memoriaOverhead /memoriaOverhead.c

CMD ["strace", "-c", "du", "/memoriaOverhead", "execvp"]
